[workspace]
default-members=["d4utils"]
members = [
	"d4-framefile",
	"d4-hts",
	"d4",
	"d4utils",
	"d4binding",
<<<<<<< Updated upstream
	"d4-bigwig",
=======
	"bigwig",
>>>>>>> Stashed changes
]

[profile.release]
debug = false
