[package]
name = "d4-hts"
version = "0.3.11"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2021"
license = "MIT"
description = "The htslib binding used by D4"
repository = "https://github.com/38/d4-format"

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
pkg-config = "0.3.18"
