#!/bin/bash

set -ex

pushd ${OUT_DIR}

if [ -z ${HTSLIB_VERSION} ]; then
	HTSLIB_VERSION="1.9"
fi

rm -rf ${OUT_DIR}/htslib

git clone -b ${HTSLIB_VERSION} https://github.com/samtools/htslib.git

cd htslib

cat > config.h << CONFIG_H
/* Default config.h generated by Makefile */
#define HAVE_LIBBZ2 1
#define HAVE_LIBLZMA 1
#ifndef __APPLE__
#define HAVE_LZMA_H 1
#endif
#define HAVE_DRAND48 1
CONFIG_H

if [ ! -z $(echo ${TARGET} | grep musl) ]
then
	sed -i 's/gcc/musl-gcc/g' Makefile
fi
if [ "${HTSLIB}" = "dynamic" ]
then
	make -j8 lib-shared
else
	make -j8 libhts.a
fi
