[package]
name = "d4"
version = "0.1.11"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The D4 file format implementation"
repository = "https://github.com/38/d4-format"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d4-framefile = { path = "../d4-framefile"}
d4-hts = { path = "../d4-hts"}
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
rand = "0.7.3"
rayon = "1.3.0"
flate2 = "1.0.14"
