[package]
name = "d4"
version = "0.1.0"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "../readme.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d4-framefile = "0.1.0"
d4-hts = "0.1.1"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
rand = "0.7.3"
rayon = "1.3.0"
flate2 = "1.0.14"
